Feature/#46 Added useCallback
MangriMen/DnD5CharlistI pull request #51
Opened 2022-06-05 22:08 UTC by MangriMen

2022-06-05 22:09 UTC, MangriMen commented
![](https://github.trello.services/images/mini-trello-icon.png) [Wrap small lambdas (arrow functions) with useCallback and bring it to the top of a component](https://trello.com/c/A7IBdPyZ/46-wrap-small-lambdas-arrow-functions-with-usecallback-and-bring-it-to-the-top-of-a-component)

2022-06-06 05:08 UTC, FFreestyler approved these changes, later dismissed

2022-06-06 08:29 UTC, StepanovRoma requested changes

2022-06-06 08:29 UTC, StepanovRoma commented on src/components/common/NavbarComponent.tsx
> +  }, []);
Empty dependency array

2022-06-06 14:30 UTC, IHiFiveI approved these changes

2022-06-07 05:46 UTC, FFreestyler approved these changes

2022-06-07 10:23 UTC, StepanovRoma approved these changes

2022-06-07 11:05 UTC, merged