Feature/#40 Implement loader on auth page
MangriMen/DnD5CharlistI pull request #57
Opened 2022-06-09 18:23 UTC by MangriMen

2022-06-09 18:23 UTC, MangriMen commented
![](https://github.trello.services/images/mini-trello-icon.png) [Implement loader on auth page](https://trello.com/c/90LlQWYu/40-implement-loader-on-auth-page)

2022-06-10 03:43 UTC, StepanovRoma requested changes

2022-06-10 03:43 UTC, StepanovRoma commented on src/ducks/auth/selectors.ts
> +export function getIsLoading(state: RootState) {
Selectors are named like selectSelectedField

2022-06-12 05:55 UTC, StepanovRoma approved these changes

2022-06-12 05:56 UTC, FFreestyler approved these changes

2022-06-13 11:11 UTC, IHiFiveI commented on src/components/pages/AuthPage.tsx
> +            {isLoading ? (
Chaining ternary is usualy a bad practice, so may be would be better use there `&&` and split it into two checks? Like `isLoading && <CircularProgress />`, `!isLoading && ...`

2022-06-13 11:14 UTC, IHiFiveI commented on src/ducks/user/index.ts
> +export { selectUser as getUser };
Why a rename on export?

2022-06-13 11:16 UTC, MangriMen commented on src/ducks/user/index.ts
> +export { selectUser as getUser };
Oh wait. VSCode auto changed export after rename

2022-06-13 11:34 UTC, merged