Feature/#38 Create user settings
MangriMen/DnD5CharlistI pull request #58
Opened 2022-06-10 16:20 UTC by StepanovRoma

1. Made a fully working page with settings, validation and display
2. Reworked authorization and now after refreshing the page the user remains logged in (redux)
3. It needs a lot of testing
4. Perhaps refactoring is definitely needed, everything will be added to separate tasks, the auth duck also needs to be finalized
![image](https://user-images.githubusercontent.com/60768837/173108603-e3de32e3-0248-4db3-98e8-ba43a0e1c1f6.png)

2022-06-10 16:20 UTC, StepanovRoma commented
![](https://github.trello.services/images/mini-trello-icon.png) [Create user settings](https://trello.com/c/e3uOvVfL/38-create-user-settings)

2022-06-11 07:49 UTC, MangriMen approved these changes

2022-06-12 05:55 UTC, FFreestyler approved these changes

2022-06-13 12:50 UTC, IHiFiveI commented on src/schemas/auth.ts
> +    .max(20, 'nick should be less 20 chars')
Replace with "Nickname can't be longer than 20 characters"

2022-06-13 12:53 UTC, IHiFiveI commented on src/locales/ru/translation.json
> +    "email": "Email",
Return old translation

2022-06-13 12:56 UTC, IHiFiveI commented on src/ducks/userSettings/index.ts
> +      state.loading = {
Replace with `state.loading = initialState.loading`

2022-06-13 12:59 UTC, IHiFiveI commented on src/ducks/user/index.ts
> +      state.user.email = '';
Replace using initialState.user

2022-06-13 13:18 UTC, MangriMen requested changes

2022-06-13 13:18 UTC, MangriMen commented on src/ducks/auth/index.ts
> +  isLogged: !auth?.currentUser,
isLogged should be changed to false, becuase firebase is loading slower than initialState and it always be false.

2022-06-13 13:18 UTC, MangriMen commented on src/ducks/auth/index.ts
> +    registerSuccess: (state, action) => {
Remove unnecessary action.

2022-06-13 13:18 UTC, MangriMen commented on src/components/App.tsx
> +
Add user argument to arrow function and check it not to be null; add dispatch loginSuccess action. Move fetchUser and loginSuccess dispatches to if statement with user check (like `if (user) {}`) and add logoutSuccess dispacth to else branch of if statement.

2022-06-13 14:35 UTC, MangriMen approved these changes

2022-06-13 14:42 UTC, IHiFiveI approved these changes

2022-06-13 14:45 UTC, merged