Feature/#39 Create main page
MangriMen/DnD5CharlistI pull request #70
Opened 2022-06-26 11:32 UTC by FFreestyler

2022-06-26 11:33 UTC, FFreestyler commented
![](https://github.trello.services/images/mini-trello-icon.png) [Create main page](https://trello.com/c/dn7upwYC/39-create-main-page)

2022-06-26 21:56 UTC, MangriMen approved these changes

2022-07-01 07:47 UTC, FFreestyler commented
![image](https://user-images.githubusercontent.com/49301790/176849490-9e035bf3-e9aa-412a-8e5a-e79cb8bf7aaf.png)

2022-07-04 03:37 UTC, StepanovRoma requested changes

2022-07-04 03:37 UTC, StepanovRoma commented on src/components/pages/Mainpage.tsx
> +  const [checked] = useState(true);
useState do nothing

2022-07-04 03:37 UTC, StepanovRoma commented on src/components/common/Navbar.tsx
> +
It is better to do this using private routing

2022-07-04 07:31 UTC, MangriMen requested changes
Rename Mainpage to MainPage

2022-07-04 09:11 UTC, MangriMen approved these changes

2022-07-10 13:51 UTC, StepanovRoma approved these changes

2022-07-10 15:06 UTC, merged