Feature/#49 Refactor routes with <Outlet />
MangriMen/DnD5CharlistI pull request #72
Opened 2022-06-27 22:44 UTC by MangriMen

2022-06-27 22:44 UTC, MangriMen commented
![](https://github.trello.services/images/mini-trello-icon.png) [Refactor routes with <Outlet />](https://trello.com/c/f3DTRXEF/49-refactor-routes-with-outlet)

2022-07-04 03:42 UTC, StepanovRoma requested changes

2022-07-04 03:42 UTC, StepanovRoma commented on src/components/App.tsx
> +        <Route path={ROUTE.ROOT} element={<PageWithNavbar />}>
I think we need to add private routing to this pr

2022-07-06 08:20 UTC, StepanovRoma approved these changes

2022-07-06 14:03 UTC, FFreestyler approved these changes

2022-07-09 08:43 UTC, merged