Feature/#66 Add user self-delete ability
MangriMen/DnD5CharlistI pull request #81
Opened 2022-08-09 17:59 UTC by MangriMen

2022-08-09 17:59 UTC, MangriMen commented
![image](https://user-images.githubusercontent.com/49300253/183726128-4ca73700-c95f-41bc-816b-2a0d18154c3a.png)

![image](https://user-images.githubusercontent.com/49300253/183726166-be0847f4-5338-4f34-98a0-ff82d119f1b8.png)

2022-08-18 03:30 UTC, StepanovRoma requested changes

2022-08-18 03:30 UTC, StepanovRoma commented on src/ducks/auth/index.ts
> +    deleteUserSuccess: () => {},
You forgot to remove loading and change the login status

2022-08-19 02:17 UTC, StepanovRoma approved these changes

2022-08-19 04:53 UTC, FFreestyler approved these changes

2022-08-19 19:28 UTC, merged