Feature/#12 Create skills field
MangriMen/DnD5CharlistI pull request #82
Opened 2022-08-15 09:43 UTC by MangriMen

2022-08-15 09:43 UTC, MangriMen commented
![image](https://user-images.githubusercontent.com/49300253/184613559-528302d2-5f3c-42bd-8a3b-48e4679b9a97.png)

2022-08-15 13:34 UTC, MangriMen commented
![](https://github.trello.services/images/mini-trello-icon.png) [Create skills field](https://trello.com/c/BJM7GegR/12-create-skills-field)

2022-08-18 03:55 UTC, StepanovRoma requested changes

2022-08-18 03:55 UTC, StepanovRoma commented on src/components/charlist/Abilities.tsx
> +export const Abilities: FC<{
The three components should be split into separate files in the same folder

2022-08-18 03:55 UTC, StepanovRoma commented on src/components/charlist/Charlist.tsx
> +    },
This long thing can be moved to a separate file, or take out the above component

2022-08-18 03:55 UTC, StepanovRoma commented on src/ducks/data/index.ts
> +    },
It's not a fact that humanity does not yet know how it should be, but personally, I have made data transformations into sagas, and in reducers I just cover the state

2022-08-19 04:51 UTC, FFreestyler approved these changes

2022-08-19 07:19 UTC, StepanovRoma approved these changes

2022-08-19 19:32 UTC, merged