Feature/#21 Add theme support
MangriMen/DnD5CharlistI pull request #83
Opened 2022-08-17 19:25 UTC by MangriMen

2022-08-17 19:26 UTC, MangriMen commented
- [ ] Fix warning with settings routes

2022-08-17 20:05 UTC, MangriMen commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add theme support](https://trello.com/c/MJbSkmkr/21-add-theme-support)

2022-08-17 20:06 UTC, MangriMen commented
![image](https://user-images.githubusercontent.com/49300253/185232780-a94b7d2e-e687-4419-89b7-2c7e7039578d.png)

![image](https://user-images.githubusercontent.com/49300253/185232816-84b19d6d-591d-4063-a131-60a505104663.png)

2022-08-18 03:47 UTC, StepanovRoma requested changes

2022-08-18 03:47 UTC, StepanovRoma commented on src/components/user/SettingSection.tsx
> +      <Box {...containerProps}>{children}</Box>
sx={{ overflow: 'hidden' }}, I think it's much better this way, or write for every single in the props

2022-08-18 03:47 UTC, StepanovRoma commented on src/components/user/SettingSection.tsx
> +      <Box {...containerProps}>{children}</Box>
![image](https://user-images.githubusercontent.com/60768837/185289046-94ed15e3-f4d4-403b-9d09-d90e7bf12f50.png)
screen with scroll bar

2022-08-19 02:13 UTC, StepanovRoma approved these changes

2022-08-19 04:48 UTC, FFreestyler approved these changes

2022-08-19 19:56 UTC, merged